# Generated by Django 4.0.4 on 2022-05-13 11:56

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='image',
            field=models.FileField(upload_to=main.models.upload_device_image),
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=1000)),
                ('deviceFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.devices')),
                ('userFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.usertech')),
            ],
        ),
    ]
