# Generated by Django 3.2.4 on 2021-11-17 11:31

from django.db import migrations, models
import django.db.models.deletion
import home.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modification')),
                ('ativo', models.BooleanField(default=True)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modification')),
                ('ativo', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(choices=[('lni-cog', 'Gear'), ('lni-starts-up', 'Graphic'), ('lni-users', 'Config'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Rocket')], max_length=13)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modification')),
                ('ativo', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('bio', models.CharField(max_length=200)),
                ('facebook', models.CharField(default='#', max_length=200, verbose_name='Facebook')),
                ('twitter', models.CharField(default='#', max_length=200, verbose_name='Twitter')),
                ('instagram', models.CharField(default='#', max_length=200, verbose_name='Instagram')),
                ('photo', stdimage.models.StdImageField(upload_to=home.models.change_name, verbose_name='Photo')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.role', verbose_name='role')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
