# Generated by Django 3.2.4 on 2021-11-03 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211027_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sales',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('quote', models.CharField(blank=True, default=None, max_length=60)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
