# Generated by Django 3.2.4 on 2021-11-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20211103_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='authorQ',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
